//syntax = "proto3";
//
//option go_package = "/agent";
//
//package main;
//
//service Calculator {
//    rpc Add (AddRequest) returns (AddResponse);
//}
//
//message AddRequest {
//    int32 a = 1;
//    int32 b = 2;
//}
//
//message AddResponse {
//    int32 result = 1;
//}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SegmentStatusList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegStatus []*SegStatus `protobuf:"bytes,1,rep,name=segStatus,proto3" json:"segStatus,omitempty"`
}

func (x *SegmentStatusList) Reset() {
	*x = SegmentStatusList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentStatusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentStatusList) ProtoMessage() {}

func (x *SegmentStatusList) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentStatusList.ProtoReflect.Descriptor instead.
func (*SegmentStatusList) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentStatusList) GetSegStatus() []*SegStatus {
	if x != nil {
		return x.SegStatus
	}
	return nil
}

type SegStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataDir    string `protobuf:"bytes,1,opt,name=dataDir,proto3" json:"dataDir,omitempty"`
	RetVal     int32  `protobuf:"varint,2,opt,name=retVal,proto3" json:"retVal,omitempty"`
	ErrMessage string `protobuf:"bytes,3,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
}

func (x *SegStatus) Reset() {
	*x = SegStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegStatus) ProtoMessage() {}

func (x *SegStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegStatus.ProtoReflect.Descriptor instead.
func (*SegStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SegStatus) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *SegStatus) GetRetVal() int32 {
	if x != nil {
		return x.RetVal
	}
	return 0
}

func (x *SegStatus) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

type SegmentConfigList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegConfig []*SegmentConfig `protobuf:"bytes,1,rep,name=segConfig,proto3" json:"segConfig,omitempty"`
}

func (x *SegmentConfigList) Reset() {
	*x = SegmentConfigList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentConfigList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentConfigList) ProtoMessage() {}

func (x *SegmentConfigList) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentConfigList.ProtoReflect.Descriptor instead.
func (*SegmentConfigList) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SegmentConfigList) GetSegConfig() []*SegmentConfig {
	if x != nil {
		return x.SegConfig
	}
	return nil
}

type SegmentConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataDir        string    `protobuf:"bytes,1,opt,name=dataDir,proto3" json:"dataDir,omitempty"`
	MaxConnections int32     `protobuf:"varint,2,opt,name=maxConnections,proto3" json:"maxConnections,omitempty"`
	SharedBuffers  string    `protobuf:"bytes,3,opt,name=sharedBuffers,proto3" json:"sharedBuffers,omitempty"`
	LcConfig       *LcStruct `protobuf:"bytes,4,opt,name=lcConfig,proto3" json:"lcConfig,omitempty"`
	PortNum        int32     `protobuf:"varint,5,opt,name=portNum,proto3" json:"portNum,omitempty"`
	Dbid           int32     `protobuf:"varint,6,opt,name=dbid,proto3" json:"dbid,omitempty"`
	ContentId      int32     `protobuf:"varint,7,opt,name=contentId,proto3" json:"contentId,omitempty"`
	CoordinatorIP  string    `protobuf:"bytes,8,opt,name=coordinatorIP,proto3" json:"coordinatorIP,omitempty"`
}

func (x *SegmentConfig) Reset() {
	*x = SegmentConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentConfig) ProtoMessage() {}

func (x *SegmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentConfig.ProtoReflect.Descriptor instead.
func (*SegmentConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentConfig) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *SegmentConfig) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *SegmentConfig) GetSharedBuffers() string {
	if x != nil {
		return x.SharedBuffers
	}
	return ""
}

func (x *SegmentConfig) GetLcConfig() *LcStruct {
	if x != nil {
		return x.LcConfig
	}
	return nil
}

func (x *SegmentConfig) GetPortNum() int32 {
	if x != nil {
		return x.PortNum
	}
	return 0
}

func (x *SegmentConfig) GetDbid() int32 {
	if x != nil {
		return x.Dbid
	}
	return 0
}

func (x *SegmentConfig) GetContentId() int32 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *SegmentConfig) GetCoordinatorIP() string {
	if x != nil {
		return x.CoordinatorIP
	}
	return ""
}

type LcStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LcCollate  string `protobuf:"bytes,1,opt,name=lcCollate,proto3" json:"lcCollate,omitempty"`
	LcCtpye    string `protobuf:"bytes,2,opt,name=lcCtpye,proto3" json:"lcCtpye,omitempty"`
	LcMessages string `protobuf:"bytes,3,opt,name=lcMessages,proto3" json:"lcMessages,omitempty"`
	LcMonetary string `protobuf:"bytes,4,opt,name=lcMonetary,proto3" json:"lcMonetary,omitempty"`
	LcNumeric  string `protobuf:"bytes,5,opt,name=lcNumeric,proto3" json:"lcNumeric,omitempty"`
	LcTime     string `protobuf:"bytes,6,opt,name=lcTime,proto3" json:"lcTime,omitempty"`
}

func (x *LcStruct) Reset() {
	*x = LcStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LcStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LcStruct) ProtoMessage() {}

func (x *LcStruct) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LcStruct.ProtoReflect.Descriptor instead.
func (*LcStruct) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *LcStruct) GetLcCollate() string {
	if x != nil {
		return x.LcCollate
	}
	return ""
}

func (x *LcStruct) GetLcCtpye() string {
	if x != nil {
		return x.LcCtpye
	}
	return ""
}

func (x *LcStruct) GetLcMessages() string {
	if x != nil {
		return x.LcMessages
	}
	return ""
}

func (x *LcStruct) GetLcMonetary() string {
	if x != nil {
		return x.LcMonetary
	}
	return ""
}

func (x *LcStruct) GetLcNumeric() string {
	if x != nil {
		return x.LcNumeric
	}
	return ""
}

func (x *LcStruct) GetLcTime() string {
	if x != nil {
		return x.LcTime
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

var file_agent_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x61, 0x69, 0x6e, 0x22, 0x42, 0x0a, 0x11, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x73, 0x65, 0x67, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x73, 0x65, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x73, 0x65,
	0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5d, 0x0a, 0x09, 0x73, 0x65, 0x67, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x72, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x46, 0x0a, 0x11, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x73,
	0x65, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x09, 0x73, 0x65, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x95,
	0x02, 0x0a, 0x0d, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61,
	0x78, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x42, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x6c, 0x63, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x6c, 0x63, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x08, 0x6c, 0x63, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x62, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x62,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x50, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x49, 0x50, 0x22, 0xb8, 0x01, 0x0a, 0x08, 0x6c, 0x63, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x63, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x63, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x63, 0x43, 0x74, 0x70, 0x79, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6c, 0x63, 0x43, 0x74, 0x70, 0x79, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6c,
	0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6c, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6c,
	0x63, 0x4d, 0x6f, 0x6e, 0x65, 0x74, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6c, 0x63, 0x4d, 0x6f, 0x6e, 0x65, 0x74, 0x61, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x63, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6c, 0x63, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x63, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x63, 0x54, 0x69, 0x6d,
	0x65, 0x32, 0x64, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x54, 0x6f, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x1a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData = file_agent_proto_rawDesc
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_proto_rawDescData)
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_proto_goTypes = []interface{}{
	(*SegmentStatusList)(nil), // 0: main.segmentStatusList
	(*SegStatus)(nil),         // 1: main.segStatus
	(*SegmentConfigList)(nil), // 2: main.segmentConfigList
	(*SegmentConfig)(nil),     // 3: main.segmentConfig
	(*LcStruct)(nil),          // 4: main.lcStruct
}
var file_agent_proto_depIdxs = []int32{
	1, // 0: main.segmentStatusList.segStatus:type_name -> main.segStatus
	3, // 1: main.segmentConfigList.segConfig:type_name -> main.segmentConfig
	4, // 2: main.segmentConfig.lcConfig:type_name -> main.lcStruct
	2, // 3: main.CliToSegmentHost.createAndConfigureSegments:input_type -> main.segmentConfigList
	0, // 4: main.CliToSegmentHost.createAndConfigureSegments:output_type -> main.segmentStatusList
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentStatusList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentConfigList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LcStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_rawDesc = nil
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
